Fixed proto files and added last changes for CreateBeneficiary in Campaigns
podkrepi-bg/types pull request #5
Opened 2021-06-19 20:38 UTC by mayapeneva

2021-06-19 22:18 UTC, imilchev commented
You should also make sure the Go types are up-to-date every time you change the proto files. Check the README for how to do that.

2021-06-20 09:50 UTC, preslavgerchev commented on protos/account.proto
> +{
The opening brace for the protobuf functions, services, responses, requests should be on the same line, not on the next one (applies for all changes below)

2021-06-20 09:54 UTC, preslavgerchev commented on protos/common/nomenclatures.proto
> +  Individual = 0;
By convention the zero should be an `Unknown` or `Unspecified` value - if the payload cannot be deserialized, the first (zero) value is used by default. 

The other PR for conventions is still open but this will either be named `Unspecified`, `UNSPECIFIED` or as the default convention suggests: `BENEFICIARY_TYPE_UNSPECIFIED`.

2021-06-20 09:55 UTC, preslavgerchev requested changes

2021-06-20 09:55 UTC, preslavgerchev commented on protos/common/nomenclatures.proto
> +  Aheloy = 0;
Same comment about default unknown value

2021-06-20 09:55 UTC, preslavgerchev commented on protos/common/nomenclatures.proto
> +/*enum ISO3CountryCode
Can we remove those if they're commented out?

2021-06-20 10:15 UTC, imilchev requested changes
Re-generate Go files

2021-06-20 11:30 UTC, mayapeneva commented on protos/common/nomenclatures.proto
> +  Individual = 0;
Oh, that with solve a problem with the validations I had in campaigns. Thank you :)

2021-06-20 13:07 UTC, mayapeneva commented
Pls let me know if it is ok to merge.

2021-06-20 13:43 UTC, imilchev approved these changes

2021-06-21 07:58 UTC, preslavgerchev approved these changes

2021-06-21 08:48 UTC, merged