Beneficiary: added DOB, region, address, connection with Beneficiary
podkrepi-bg/types pull request #8
Opened 2021-07-06 21:57 UTC by mayapeneva

2021-07-06 22:04 UTC, imilchev commented on protos/campaign.proto
> +  string organizer_id = 5;
I see the ordering of the properties has changed. This is not an issue as long as nothing is using that message apart from the campaign modules. Is that the case?

2021-07-06 22:08 UTC, mayapeneva commented on protos/campaign.proto
> +  string organizer_id = 5;
Campaign.proto is used by campaigns module only I think. 
Should I add the new fields at the end, not among the other fields?

2021-07-07 05:19 UTC, preslavgerchev commented on protos/campaign.proto
> +  string organizer_id = 5;
Protobuf makes use of the number to indicate which field represents what when in a binary format. If someone is using an older definition of the `campaign.proto` they'd expect that `5` is the country code whereas on our side we will parse this as an `organizer_id` - generally new fields indeed go at the end

2021-07-07 05:22 UTC, preslavgerchev commented on protos/common/nomenclatures.proto
> +enum Connection {
I think this should be in `campaign.proto` - it's pretty unique to a beneficiary and will likely not be used by the other proto files

2021-07-07 05:22 UTC, preslavgerchev commented on protos/common/nomenclatures.proto
> +enum Connection {
Also, consider renaming to `BeneficiaryConnection` to make it a bit more explicit

2021-07-07 21:12 UTC, mayapeneva commented on protos/common/nomenclatures.proto
> +enum Connection {
Thank you

2021-07-08 08:20 UTC, preslavgerchev requested changes

2021-07-08 08:20 UTC, preslavgerchev commented on protos/campaign.proto
> +  BENEFICIARY_CONNECTION_AUNTCONNECTION_OTHER = 15;
Think these are supposed to be 2 values

2021-07-08 17:21 UTC, mayapeneva commented on protos/campaign.proto
> +  BENEFICIARY_CONNECTION_AUNTCONNECTION_OTHER = 15;
Sure. Thank you.

2021-07-08 19:55 UTC, preslavgerchev approved these changes

2021-07-09 06:05 UTC, merged